# Datos de alumno

Estudiante: Octavio Quintero Flores

Matricula: 266226

Maestría en Inteligencia Artificial y Analítica de Datos

#Instrucciones

##Ejercicio 01: Errores Tipográficos y Valores Inconsistentes: maritalstatus

*  Imprime de la columna 'maritalstatus' los valores únicos.
*  Imprime la frecuencia de cada valor único
*  Cambia el valor 'Never-Married' a 'Single'
*  Imprime la frecuencia de cada valor único.

##Ejercicio 02: Errores Tipográficos y Valores Inconsistentes: highestdegree.

* Imprime de la columna 'highestdegrees' los valores únicos.
* Imprime la frecuencia de cada valor único
* Observa que cada valor categórico empieza con 0. Modifica las categorías para que todas estén en minúsculas y ninguna empiece con un número. Por ejemplo, si dice "2. High School", debería ser 'high school.
* Los cambios se realizarán en la misma columna 'highestdegrees'.
* Imprime los nuevos valores únicos.

##Ejercicio 03: Alta Cardinalidad - Frecuencias Bajas

* De la columna 'maritalstatus' une las categorías Widowed y 'Single' en una categoría más general llamada 'Single/No Partner'. Crea una nueva columna, 'marital_grouped' donde aparezcan las nuevas categorías de maritalstatus.
* Imprime los valores únicos de la nueva columna 'marital_grouped'.
* Imprime la frecuencia de los valores únicos de la nueva columna 'marital_grouped'

##Ejercicio 04: Tipos de Datos

* Imprime el tipo de datos de la columna gender
* Imprime la cantidad de bytes de dicha columna
* Si la columna es de tipo object, modifica a category.
* En caso de haber realizado la modificación del tipo de datos, imprime la cantidad de bytes que ocupa dicha columna con el nuevo tipo de datos

#Desarrollo

Conectamos nuestro drive para utilizar el archivo csv, cargaremos el archivo en un df, ademas de cargar librerias que utilizaremos.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/drive/MyDrive/ClassFiles/nls97.csv")

Observamos como se encuentra el df

In [4]:
df.head()

,personid,gender,birthmonth,birthyear,highestgradecompleted,maritalstatus,childathome,childnotathome,wageincome,weeklyhrscomputer,...,colenrfeb13,colenroct13,colenrfeb14,colenroct14,colenrfeb15,colenroct15,colenrfeb16,colenroct16,colenrfeb17,colenroct17
0,100061,Female,5,1980,13.0,Married,4.0,0.0,12500.0,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
1,100139,Male,9,1983,12.0,Married,2.0,0.0,120000.0,1 to 3 hours a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
2,100284,Male,11,1984,7.0,Never-married,1.0,0.0,58000.0,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
3,100292,Male,4,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,NaN,NaN,NaN,NaN
4,100583,Male,1,1980,13.0,Married,4.0,0.0,30000.0,Less than 1 hour a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled

In [20]:
df.describe(include='all')

,personid,gender,birthmonth,birthyear,highestgradecompleted,maritalstatus,childathome,childnotathome,wageincome,weeklyhrscomputer,...,colenrfeb13,colenroct13,colenrfeb14,colenroct14,colenrfeb15,colenroct15,colenrfeb16,colenroct16,colenrfeb17,colenroct17
count,8984.000000,8984,8984.000000,8984.000000,6663.000000,6672,4791.000000,4791.000000,5091.000000,5792,...,7754,7754,7624,7469,7469,7469,7036,6733,6733,6734
unique,NaN,2,NaN,NaN,NaN,5,NaN,NaN,NaN,5,...,4,4,4,4,4,4,4,4,4,4
top,NaN,Male,NaN,NaN,NaN,Married,NaN,NaN,NaN,10 hours or more a week,...,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled,1. Not enrolled
freq,NaN,4599,NaN,NaN,NaN,3066,NaN,NaN,NaN,3669,...,7051,7044,6974,6883,6915,6905,6567,6310,6338,6348
mean,548677.477627,NaN,6.555988,1982.010352,14.059883,NaN,1.859320,0.410144,49477.022196,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,261136.320796,NaN,3.469429,1.396870,4.507592,NaN,1.259053,0.947590,40677.696798,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,100061.000000,NaN,1.000000,1980.000000,5.000000,NaN,0.000000,0.000000,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,322251.750000,NaN,3.000000,1981.000000,12.000000,NaN,1.000000,0.000000,25000.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,549182.000000,NaN,7.000000,1982.000000,14.000000,NaN,2.000000,0.000000,40000.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,777824.000000,NaN,10.000000,1983.000000,16.000000,NaN,3.000000,0.000000,62000.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,999963.000000,NaN,12.000000,1984.000000,95.000000,NaN,9.000000,12.000000,235884.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Ejercicio 1

In [31]:
df['maritalstatus'].unique()

array(['Married', 'Never-Married', nan, 'Divorced', 'Separated',
       'Widowed'], dtype=object)

In [32]:
df['maritalstatus'].value_counts()

maritalstatus
Married          3066
Never-Married    2766
Divorced          663
Separated         154
Widowed            23
Name: count, dtype: int64

In [33]:
df['maritalstatus'] = df['maritalstatus'].replace('Never-Married', 'Single')

In [34]:
df['maritalstatus'].value_counts()

maritalstatus
Married      3066
Single       2766
Divorced      663
Separated     154
Widowed        23
Name: count, dtype: int64

##Comentarios
Podemos ver cuales eran los valores unicos que se presentaban en la columna ademas de realizar el conteo por cada uno de estos valores unicos.

#Ejercicio 2

In [37]:
df['highestdegrees'].unique()

KeyError: 'highestdegrees'

Al no encontrar el nombre como lo marcaba el ejercicio, decidi buscar las columnas para ver si existia alguno con algun nombre similiar y si los datos cooresponden a lo que se pide.

In [39]:
df.columns

Index(['personid', 'gender', 'birthmonth', 'birthyear',
       'highestgradecompleted', 'maritalstatus', 'childathome',
       'childnotathome', 'wageincome', 'weeklyhrscomputer', 'weeklyhrstv',
       'nightlyhrssleep', 'satverbal', 'satmath', 'gpaoverall', 'gpaenglish',
       'gpamath', 'gpascience', 'highestdegree', 'govprovidejobs',
       'govpricecontrols', 'govhealthcare', 'govelderliving', 'govindhelp',
       'govunemp', 'govincomediff', 'govcollegefinance', 'govdecenthousing',
       'govprotectenvironment', 'weeksworked00', 'weeksworked01',
       'weeksworked02', 'weeksworked03', 'weeksworked04', 'weeksworked05',
       'weeksworked06', 'weeksworked07', 'weeksworked08', 'weeksworked09',
       'weeksworked10', 'weeksworked11', 'weeksworked12', 'weeksworked13',
       'weeksworked14', 'weeksworked15', 'weeksworked16', 'weeksworked17',
       'colenrfeb97', 'colenroct97', 'colenrfeb98', 'colenroct98',
       'colenrfeb99', 'colenroct99', 'colenrfeb00', 'colenroct00',
       'colenrfeb01', 'colenroct01', 'colenrfeb02', 'colenroct02',
       'colenrfeb03', 'colenroct03', 'colenrfeb04', 'colenroct04',
       'colenrfeb05', 'colenroct05', 'colenrfeb06', 'colenroct06',
       'colenrfeb07', 'colenroct07', 'colenrfeb08', 'colenroct08',
       'colenrfeb09', 'colenroct09', 'colenrfeb10', 'colenroct10',
       'colenrfeb11', 'colenroct11', 'colenrfeb12', 'colenroct12',
       'colenrfeb13', 'colenroct13', 'colenrfeb14', 'colenroct14',
       'colenrfeb15', 'colenroct15', 'colenrfeb16', 'colenroct16',
       'colenrfeb17', 'colenroct17'],
      dtype='object')

Observamos que si se encuentra un highestdegree usare unique para ver los valores unicos ademas de comprobar si es lo que se nos pide

In [40]:
df['highestdegree'].unique()

array(['2. High School', '0. None', '4. Bachelors', '3. Associates',
       '5. Masters', '1. GED', '7. Professional', '6. PhD', nan],
      dtype=object)

In [41]:
df['highestdegree'].value_counts()

highestdegree
2. High School     3667
4. Bachelors       1673
1. GED             1146
0. None             953
3. Associates       737
5. Masters          603
7. Professional     120
6. PhD               54
Name: count, dtype: int64

Con regex hare la normalizacion y para que este minusculas con lower

In [43]:
df['highestdegree'] = (
    df['highestdegree']
    .str.replace(r'^\d+\.\s*', '', regex=True)
    .str.lower()
)

In [46]:
df['highestdegree'].unique()

array(['high school', 'none', 'bachelors', 'associates', 'masters', 'ged',
       'professional', 'phd', nan], dtype=object)

In [45]:
df['highestdegree'].value_counts()

highestdegree
high school     3667
bachelors       1673
ged             1146
none             953
associates       737
masters          603
professional     120
phd               54
Name: count, dtype: int64

##Comentarios

Me gusto como se presento el caso donde no existia la columna ya que eso es algo que pasa en la vida real, o que por un caracter cambia.

#Ejercicio 3

Creare el marital_grouped y usare replace junto con [] para agarrar un conjunto de valores y reemplazarlos por uno.

In [54]:
df['marital_grouped'] = df['maritalstatus'].replace(["Widowed",'Single'],"Single/No Partner")

In [55]:
df['marital_grouped'].value_counts()

marital_grouped
Married              3066
Single/No Partner    2789
Divorced              663
Separated             154
Name: count, dtype: int64

In [56]:
df['marital_grouped'].unique()

array(['Married', 'Single/No Partner', nan, 'Divorced', 'Separated'],
      dtype=object)

#Ejercicio 4

In [58]:
df['gender'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8984 entries, 0 to 8983
Series name: gender
Non-Null Count  Dtype
--------------  -----
8984 non-null   object
dtypes: object(1)
memory usage: 70.3+ KB

In [60]:
df['gender'].dtypes

dtype('O')

In [61]:
df['gender'].memory_usage(deep=True)

485054

In [62]:
if df['gender'].dtype == 'object':
    df['gender'] = df['gender'].astype('category')

In [63]:
df['gender'].memory_usage(deep=True)

9332

##Comentarios

Me gusto mucho ver las diferencias de tipos de datos y como nos pega en el uso de memoria y la optimizacion.