# Datos de alumno

Estudiante: Octavio Quintero Flores

Matricula: 266226

Maestría en Inteligencia Artificial y Analítica de Datos

#Instrucciones

Descarga el archivo airdata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
Crea un notebook en colab y guarda el archivo csv  en tu drive.
Agrega secciones en el colab poniendo como título el nombre de cada ejercicio

##Ejercicio 01:Tipo de Datos Correcto

* Carga el conjunto de datos airdata.csv y verifica que cada columna tenga el tipo de datos correcto
* Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión.
* Usa dtypes para mostrar que cada columna, principalmente la que contiene datos temporales, está en el tipo de datos correcto
* Imprime las primeras tres líneas

##Ejercicio 02: Extraer componentes de fecha y tiempo

* De la columna 'DateTime' extrae el año, mes, día y hora. Crea una nueva columna para cada componente que extraes
* Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

##Ejercicio 03: Aritmética - Suma de Intervalos (timedelta)

* Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'.
* Guarda el resultado en una nueva columna y agrega al dataframe.
* Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

##Ejercicio 04: Timestamp

* Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a a timestamp Unix.
* Guarda el resultado en una nueva columna
* Imprime las primeras tres filas de  la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix


##Ejercicio 05: Filtrado de Fechas

* Utiliza la columna 'DateTime' y Filtra aquellas fechas que son mayores a 2020-11-01
* Imprime el resultado

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np

Mounted at /content/drive

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Unidad02/Airdata.csv')

#Ejercicio 1

In [4]:
df['DateTime'] = pd.to_datetime(df['DateTime'],errors='coerce')
print(df.dtypes)

DateTime          datetime64[ns]
Temperature              float64
Humidity                   int64
Wind_Speed               float64
Wind_Direction           float64
NO2_Location_A           float64
NO2_Location_B           float64
NO2_Location_C           float64
dtype: object

In [5]:
df.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80

#Ejercicio 2

In [6]:
df['Year'] = df['DateTime'].dt.year
df['Month'] = df['DateTime'].dt.month
df['Day'] = df['DateTime'].dt.day
df['Hour'] = df['DateTime'].dt.hour
df.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C,Year,Month,Day,Hour
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37,2020,1,1,0
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53,2020,1,1,1
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80,2020,1,1,2

#Ejercicio 3

In [9]:
intervalo = pd.Timedelta(days=10, hours=7, minutes=15)
df['DateTime_suma'] = df['DateTime'] + intervalo
df[['DateTime','DateTime_suma']].head(3)

             DateTime       DateTime_suma
0 2020-01-01 00:00:00 2020-01-11 07:15:00
1 2020-01-01 01:00:00 2020-01-11 08:15:00
2 2020-01-01 02:00:00 2020-01-11 09:15:00

#Ejercicio 4

In [10]:
df['DateTime_unix'] = df['DateTime'].astype(np.int64) // 10**9
df[['DateTime','DateTime_unix']].head(3)

             DateTime  DateTime_unix
0 2020-01-01 00:00:00     1577836800
1 2020-01-01 01:00:00     1577840400
2 2020-01-01 02:00:00     1577844000

#Ejercicio 5

In [11]:
filtrar = df['DateTime'] > '2020-11-01'
df[filtrar].head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C,Year,Month,Day,Hour,DateTime_suma,DateTime_unix
7321,2020-11-01 01:00:00,13.620529,58,6.638072,130.60129,17.50,23.88,44.07,2020,11,1,1,2020-11-11 08:15:00,1604192400
7322,2020-11-01 02:00:00,13.980529,40,6.618519,157.61987,13.38,18.92,35.80,2020,11,1,2,2020-11-11 09:15:00,1604196000
7323,2020-11-01 03:00:00,13.010529,43,8.209263,164.74487,11.95,13.95,30.15,2020,11,1,3,2020-11-11 10:15:00,1604199600